ＡIプログラミング2 2回目<br>
numpyの勉強

#1.リストに数値を加算<br>
まだnumpyではない

In [5]:
L1=[1, 3, 7, 9]

#リストに1を足して、リストの要素全部に１を足したい。
#これはエラーになる。
#L2=L1+1
#forをつかわないといけない。

L2=[]
for i in L1:
  L2.append(i+1)
print("L2:", L2)

#内包表記を使う場合
L3=[i+1 for i in  L1]
print("L3:", L3)


L2: [2, 4, 8, 10]
L3: [2, 4, 8, 10]


#2.numpyを使って数学の式のように書く<br>
(1)numpyで計算させた方が早く計算せることができる。

In [6]:
import numpy as np

#リストというより、ベクトルを操作と考える。
L4=[2,4,13, 17]

N1=np.array(L4)

print("N1:", type(N1))

#ここの部分(重要)
N2 = N1 + 3


print("N2:", N2)

N1: <class 'numpy.ndarray'>
N2: [ 5  7 16 20]


(2)2つのリストの要素をたす。<br>
numpyではない

In [ ]:
L5=[2, 3, 4]
L6=[1, 7, 9]

#後ろに追加されるだけ。
L7 = L5+L6
print("L7:", L7)

#forでつくる
L8=[]
for (i,j) in zip(L5,L6):
  L8.append(i+j)
print("L8:", L8)

L9=[i+j for (i,j) in zip(L5,L6)]
print("L9:", L9)

L7: [2, 3, 4, 1, 7, 9]
L8: [3, 10, 13]
L9: [3, 10, 13]


(3)numpyで2つのリストの要素をたす。

In [ ]:
L10=[2, 3, 4]
L11=[1, 7, 9]

N3=np.array(L10)
N4=np.array(L11)

#ここが処理させたいところ
N5 = N3+N4

print("N5:", N5)


N3= [2 3 4]
N4= [1 7 9]
N5: [ 3 10 13]


データの型を確認

In [ ]:
print("L10の型",type(L10))
print("N5の型", type(N5))

#形の確認
print("L10の形", len(L10))
print("N5の形", N5.shape)

L10の型 <class 'list'>
N5の型 <class 'numpy.ndarray'>
L10の形 3
N5の形 (3,)


#3.numpyで行列の計算(AIは行列計算の塊）

(1)行列の演算(+,べき乗)

In [ ]:
#2次元リスト　3x3の行列
L1=[[1,3,6],[2,6,12],[3,9,18]]

#numpyで行列に変換
M1=np.array(L1)

#行列の足し算
M2 = M1+M1

print("M2:\n", M2)

#行列のべき乗
M3 = M2**3

print("M3:\n", M3)

M2:
 [[ 2  6 12]
 [ 4 12 24]
 [ 6 18 36]]
M3:
 [[    8   216  1728]
 [   64  1728 13824]
 [  216  5832 46656]]


(2)ニューラルネットワークのパラメータを初期化するのに使う。<br>
行列のデータをすべて０にする。

In [ ]:
Z = np.zeros((3,3))
print("Z:\n", Z)

#型と形状を調べる
print("zのtype:",type(Z))
print("zのshape:",Z.shape)


Z:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
zのtype: <class 'numpy.ndarray'>
zのshape: (3, 3)


(3)形と値を指定して、要素が指定した値で埋める。

In [ ]:
f = np.full((3,2), 9)
print("f:\n", f)

#型と形状を調べる
print("fのtype:",type(f))
print("fのshape:",f.shape)

f:
 [[9 9]
 [9 9]
 [9 9]]
fのtype: <class 'numpy.ndarray'>
fのshape: (3, 2)


(4)単位行列を作る

In [ ]:
I = np.eye(3)
print("I:\n", I)

#型と形状を調べる
print("Iのtype:",type(I))
print("Iのshape:",I.shape)

I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Iのtype: <class 'numpy.ndarray'>
Iのshape: (3, 3)


(5)単位行列を掛けてみる

In [ ]:
L1=[[1,3,6],[2,6,12],[3,9,18]]
M1=np.array(L1)

print("M1:\n", M1)
#単位行列を掛ける
M3 = M1*I

print("M3\n", M3)

M1:
 [[ 1  3  6]
 [ 2  6 12]
 [ 3  9 18]]
M3
 [[ 1.  0.  0.]
 [ 0.  6.  0.]
 [ 0.  0. 18.]]


(6)行列の積**(重要)**

In [ ]:
A = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#行列の積は数学だとC？D?どっち？
C = np.dot(A, B)

print("C:\n",C)

D =A*B
print("D:\n",D)


C:
 [[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
D:
 [[ 0  2  6]
 [12 20 30]
 [42 56 72]]


#課題1<br>
2x3の行列と3x2の行列の積をnumpyで計算せよ。

In [ ]:
W1=[[1, 2, 3],[4, 5, 6]]
W2=[[7, 8],[9, 10],[11, 12]]

MW1=np.array(W1)
MW2=np.array(W2)

MC= np.dot(MW1, MW2)

print("MCの形状:", MC.shape)
print("MC:\n", MC)

MCの形状: (2, 2)
MC:
 [[ 58  64]
 [139 154]]


#課題2
1x3のベクトルと3x3の行列を掛けた後、<br>
各要素をb倍した結果を求めよ。<br>
MA・x + bの計算<br>
MA,x,bは各自オリジナル

In [9]:
x=[1, 2, 3]
x=np.array(x)

W1=[x,x+1,x+2]
MA=np.array(W1)

b=3
I=np.full(3,1)

Y=np.dot(MA, x)+b
print("計算結果",Y )


計算結果 [17 23 29]
