ＡIプログラミング2 2回目<br>
numpyの勉強

#4.numpyで行列の計算(その２）

In [ ]:
#一度はインポートしておこう
import numpy as np

(1)逆行列

In [ ]:
W3=[[1,2],[4,5]]

MW3=np.array(W3)

MW4 =
#MW4=MW3.I

print("MW3\n",MW3)
print("MW4\n",MW4)

X=
print("X\n",X)

MW3
 [[1 2]
 [4 5]]
MW4
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
X
 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


#課題3<br>
連立方程式の解の計算


In [ ]:
M=np.array([[],[]])
y=np.array([])

#逆行列の計算
MI=

x=

print("連立方程式の解:\n",x)



連立方程式の解:
 [0.33333333 0.33333333]


#5.numpyのreshape 1次元を3行3列に変換する。

In [ ]:
L=[1,3,5,2,4,6,2,3,7]

#形状変換
MB=np.reshape(L, (3, 3))

print("MB:\n", MB)
print("MBのtype", type(MB))
print("MBのshape", MB.shape)

MB:
 [[1 3 5]
 [2 4 6]
 [2 3 7]]
MBのtype <class 'numpy.ndarray'>
MBのshape (3, 3)


#numpyで提供されている関数

(1)合計sumと平方根sqrt<br>
ベクトルの大きさの計算

In [ ]:
L= [1,3,5,2,4,6,2,3,7]
N=np.array(L)

#各要素の自乗
N2=N*N
print(N2)

#自乗した後、各要素を合計
print(np.sum(N2))
#自乗した後、各要素を合計したものを平方根をとる。
print("Lのベクトルの大きさ:", np.sqrt(np.sum(N2)))

[ 1  9 25  4 16 36  4  9 49]
153
Lのベクトルの大きさ: 12.36931687685298


#6.行列の形状変換<br>
ニューラルのパラメータはまとめられることが多いので

In [ ]:
L= [1,3,5,2,4,6]
#Lを3x2の行列に変換
MC = np.reshape(L, (3, 2))

MD = np.sin(MC)

print("MC\n",MC)
print("MD\n", MD)

MC
 [[1 3]
 [5 2]
 [4 6]]
MD
 [[ 0.84147098  0.14112001]
 [-0.95892427  0.90929743]
 [-0.7568025  -0.2794155 ]]


#課題4<br>
MA・x + bの計算結果の正規化せよ。<br>
MA・x + bの計算のベクトルの大きさを計算した後、<br>
各要素を大きさで割ればよい。<br>
プログラムはnp.linalg.normは使わないで、<br>
上セルを組み合わせる

In [ ]:
#前半は課題2と同じ
x=[1, 2, 3]
x=np.array(x)

W1=[x,x+3,x+3*2]
MA=np.array(W1)

b=3
I=np.full(3,1)

Y=np.dot(MA, x)+b
print("計算結果",Y)

#後半は、ベクトルの大きさを求める。
#各要素の自乗
N2=Y*Y
print(N2)
#SIZEにベクトル大きさが入る
SIZE=np.sin(N2)

#ベクトルの各要素を大きさで割る
Y1=Y/SIZE

print("Y1:",Y1)




計算結果 [17 35 53]
[ 289 1225 2809]
Y1: [-641.00098023 -159.57177986  131.10431975]
