ＡIプログラミング2 3,4回目<br>
numpyの勉強

In [40]:
#numpyのインポート(初めに実行)
import numpy as np

#7.行列への形状変換<br>
nxmの形の行列に変形<br>
ニューラルのパラメータはまとめられることが多いので

In [5]:
L= [1,3,5,2,4,6]
#Lを3x2の行列に変換
MC = np.reshape(L, (3, 2))

MD = np.sin(MC)

print("MC\n",MC)
print("MD\n", MD)

MC
 [[1 3]
 [5 2]
 [4 6]]
MD
 [[ 0.84147098  0.14112001]
 [-0.95892427  0.90929743]
 [-0.7568025  -0.2794155 ]]


#課題4<br>
2x4の行列を8x1に変換後、4x2の行列に変換しなさい。

In [9]:
M1= np.array([[1,3,5,7], [2,4,6,8]])
print("M1\n",M1)

#M1をベクトル8x1に変換
L = np.reshape(M1, (8, ))
print("L:", L)

#Lを4x2の行列に変換
M2 = np.reshape(L, (4, 2))

print("M2\n",M2)

M1
 [[1 3 5 7]
 [2 4 6 8]]
L: [1 3 5 7 2 4 6 8]
M2
 [[1 3]
 [5 7]
 [2 4]
 [6 8]]


# 8.行の一部の切り取り<br>
多層ニューラルネットワークのパラメータを切り出すのに使われる

(1)1次元の切りだし

In [7]:
L= [1,3,5,2,4,6, 3,3,3]

N=np.array(L)
print("N:", N)

#切り出し３から4(5-1)までを切り取る
N1=N[3:5]
print("N1:", N1)

#切り出し範囲を0にする。反映箇所に注意
N[3:5]=0
print("N1", N1)
print("N", N)

#全範囲の取り出し
print("N[:]", N[:])

N: [1 3 5 2 4 6 3 3 3]
N1: [2 4]
N1 [0 0]
N [1 3 5 0 0 6 3 3 3]
N[:] [1 3 5 0 0 6 3 3 3]


(2)2次元配列

In [11]:
L= [1,3,5,2,4,6, 3,3,3]
#Lを3x3の行列に変換
M =np.reshape(L, (3, 3))
print("M\n",M)

#1要素へのアクセス
print("M", M[1][1])

#行へのアクセス1
L1=M[2]
print("L1", L1)


#行へのアクセス
L3=M[1, :]
print("L3", L3)

#範囲へのアクセス1
M1=M[:2, 1:]
print("M1\n", M1)

#範囲へのアクセス2
M2=M[:, 0:2]
print("M2\n", M2)

#範囲へのアクセス3
M3=M[1:, :]
print("M3\n", M3)

M
 [[1 3 5]
 [2 4 6]
 [3 3 3]]
M 4
L1 [3 3 3]
L3 [2 4 6]
M1
 [[3 5]
 [4 6]]
M2
 [[1 3]
 [2 4]
 [3 3]]
M3
 [[2 4 6]
 [3 3 3]]


#課題5<br>
W1は(3,2)、W2は(2x2)の行列、X=[3,2,1]に対して、<br>
W2(W1 X) を計算しなさい。<br>
Z1=W1・X, Z2=W2・Z1で計算する。

In [12]:
#こちらはreshapeしていないのであくまで参考に
X=np.array([3, 2,1])

W1=np.array([[1,2,3],[3,1,2]])
W2=np.array([[2,1], [1,3]])

print("W1:",W1)
print("W2",W2)

#行と列の数が合うか気を付ける
Z1=np.dot(W1, X)
Z2=np.dot(W2, Z1)

print("Z2:", Z2)

W1: [[1 2 3]
 [3 1 2]]
W2 [[2 1]
 [1 3]]
Z2: [33 49]


In [35]:
X=np.array([3, 2,1])

W=np.array([1,2,3,3,1,2, 2,1,1,3])

#行列の行列変換
W1=np.reshape(W[0:3*2], (2, 3))
W2=np.reshape(W[6:10], (2, 2))

print("W1:\n", W1)
print("W2:\n", W2)

#行と列の数が合うか気を付ける
Z1=np.dot(W1, X)
Z2=np.dot(W2, Z1)

print("Z2:", Z2)

W1:
 [[1 2 3]
 [3 1 2]]
W2:
 [[2 1]
 [1 3]]
Z2: [33 49]


#課題6<br>
W1 (2x2の行列)とW2 (2x3の行列)のパラメータがWにまとめられている。<br>
W1は(2,2)、W2は(3x2)の行列、X=[2,9]に対して、<br>
W2(W1 X) を計算しなさい。<br>
Z1=W1・X, Z2=W2・Z1で計算する。

In [38]:
#こちらはreshapeしていないのであくまで参考に
X=np.array([2,9])
W=np.array([1,2,3,3,1,2, 2,1,1,3])

W1=np.array([[1,2],[3,4]])
W2=np.array([[2,1],[3,4],[3,4]])

#行と列の数が合うか気を付ける

Z1=np.dot(W1,X)
Z2=np.dot(W2,Z1)

print("Z1:", Z1)
Z2=np.dot(W2,Z1)
print("Z2:", Z2)

Z1: [20 42]
Z2: [ 82 228 228]


In [55]:
#こちらはreshapeしていないのであくまで参考に
X=np.array([2,9])
W=np.array([1,2,3,4, 2,1,3,4,3,4])

W1=np.reshape(W[0:2*2], (2,2))
W2=np.reshape(W[2*2:], (3,2))

print("W1", W1)
print("W2", W2)

#行と列の数が合うか気を付ける

Z1=np.dot(W1,X)
print("Z1:", Z1)
Z2=np.dot(W2,Z1)
print("Z2:", Z2)

W1 [[1 2]
 [3 4]]
W2 [[2 1]
 [3 4]
 [3 4]]
Z1: [20 42]
Z2: [ 82 228 228]
